version: "2"
volumes:
  takebot-redis-data: { driver: local }
  takebot-sync: { external: true }
  takebot-config: { driver: local }

services:
  ########################
  # Third-party services #
  ########################

  redis:
    image: redis:5.0.0
    volumes:
      - takebot-redis-data:/data
    ports:
      - "16379:6379"

  #####################################
  # Development-specific applications #
  #####################################

  takebot:
    image: node:11.0.0
    command: ["bin/takebot"]
    environment:
      HISTFILE: "/config/.bash_history"
      CHOKIDAR_USEPOLLING: "true"
      API_BASE_URL: "http://localhost:3000"
    links:
      - redis
    volumes:
      - 'takebot-sync:/app:nocopy'
      - 'takebot-config:/config'
    ports:
      - "3000:3000" # express
      - "1234:1234" # parcel
      - "2345:2345" # parcel ws
    working_dir: /app
